# Generated by Django 6.0.4 on 2026-05-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_recommendation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorite",
            options={"ordering": ["-added_at"]},
        ),
        migrations.AlterModelOptions(
            name="movie",
            options={"ordering": ["-cached_at"]},
        ),
        migrations.AlterModelOptions(
            name="rating",
            options={"ordering": ["-rated_at"]},
        ),
        migrations.AlterModelOptions(
            name="recommendationcache",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="searchhistory",
            options={"ordering": ["-searched_at"]},
        ),
        migrations.AlterModelOptions(
            name="watchlist",
            options={"ordering": ["-added_at"]},
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["-cached_at"], name="movie_recom_cached__c0218d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["user", "rating"], name="movie_recom_user_id_8a0594_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendationcache",
            index=models.Index(
                fields=["user", "cache_type"], name="movie_recom_user_id_d77c1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchhistory",
            index=models.Index(
                fields=["user", "-searched_at"], name="movie_recom_user_id_3d18f8_idx"
            ),
        ),
    ]
