# Generated by Django 6.0.4 on 2026-04-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
